#!/bin/bash
ifs=$IFS
IFS='\
'
PDFARGUMENTS=""
fpaths=`echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sort`
for file in $fpaths
do
  if [ -f "$file" ]; then
  base=${file%.*}
	ext=${file##*.}
	if [ "$ext" == "pdf" ]; then
	    PDFARGUMENTS="$PDFARGUMENTS \"$file\""
	    #pdfdir=`dirname "$file"`
	fi
  fi
done

#szSavePath=$(zenity --file-selection --save --confirm-overwrite);echo "$szSavePath"

if [ -n "$PDFARGUMENTS" ]; then
#    eval pdftk "$PDFARGUMENTS" cat output "$szSavePath"
    eval pdftk "$PDFARGUMENTS" cat output "merge_result.pdf"
fi
IFS=$ifs
